### PR TITLE
Add Rectangular Matrix Support

### PR DESCRIPTION
**Pull request by kjkjava**
The original documentation mentions support for rectangular matrices, but it gets into an infinite loop if one is used.  I added support for rectangular matrices, documented the changes, made a few minor cosmetic changes, and added a main method to test it all out.  This code has served me well for shape matching!

### CODE REVIEW

**Comment by w01fe** [comment]
This looks really great, thanks!  Only two comments: 
- I think the code currently works on negative numbers, so it seems like a shame to break that unless it's a good reason.  What's the reason?
- Getting out the assignment would obviously be useful.  If you want, rather than switching the commented section, you could create a new method that returns the assignment and then just _call_ that from the existing method that returns the cost.  Does that make sense? 

I totally understand if you don't feel like making more changes -- I'll take the pull request either way.  Thanks again!

**Comment by kjkjava** [comment]
Thanks for looking over it and for the helpful review!

For the first point, I agree that the unnecessary restrictions are not ideal, and I think we can do better.  As you suggested, padding the matrix with some value to make it square avoids having to rework the algorithm.  Unless I'm mistaken, that value needs to be either larger than or less than all other values, so that the padded columns all get assigned first or last.  Either way, they will get thrown out in the end.  Does that sound right?

My original choice (in my JavaScript implementation) was Number.MAX_VALUE, but that didn't work due to arithmetic used in the algorithm causing overflow.  I believe I saw 99,999 used in one implementation, and I think I saw another request only positive numbers, so I figured -1 would be okay.  Perhaps the best bet is to use the findLargest or findSmallest method to pick a value one larger/smaller than the largest/smallest real value?  That'll require yet another iteration of the matrix, but considering everything else going on, that's probably not a big deal.  (If it's important, the original matrix copy could return the max or min.)  Do you think that's the best solution?

For the second point, I would probably add a method to get the sum given a matrix and an assignment array, then change hgAlgorithm to return the assignment array.  In my JavaScript implementation, I added a third parameter to choose what is returned, but that'd be unnatural in a strongly typed language.  I didn't want to change much there as not to break your code, assuming it used hgAlgorithm to get the min/max, but I'd be happy to.

Sorry to elaborate so much, but I am interested in your feedback!

-Kyle

**Comment by w01fe** [comment]
I believe you're right about the padded values.  Ideally they would just be ignored by the algorithm (not contributing to the sum) and could just be Double/NaN, but it's probably not coded that way currently, and I'm not sure how much work it would be to change it.  An intermediate solution would be to only require positive values for non-square matrices -- let the core solver operate on arbitrary values, and only make a new solveRectangular method impose this restriction.

For the second point, that's _almost_ what I meant.  My suggestion was to do this, but without any breaking changes, by creating a new function hgAlgorithmAssignments that returns the actual assignment, and then hgAlgorithm just composes hgAlgorithmAssignments and getAssignmentSum.  Does that make sense?

**Comment by kjkjava** [comment]
Do you think a separate solveRectangular method (that pads with -1) would be preferable to my other suggestion of using max+1 and imposing no restrictions?  The max could be calculated when copying the array, so it wouldn't take any longer and it would be more robust, like you originally suggested.

The second point is clear now.  Sounds good.  Thanks!

**Comment by w01fe** [comment]
Sorry, I somehow missed that bit -- max+1 or min-1 does sound like a better
approach, thanks!

**Comment by kjkjava** [comment]
All should be good now.  Let me know what you think.

**Comment by w01fe** [comment]
Merged.  Great work, I really appreciate it!

**Comment by kjkjava** [comment]
No problem!  Glad to help.

**Pull request merged**
